# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions 
 
name: (classic) Build and Deploy Logic App. 

env:
  LA_NAME: 'ais-demo-dev'
  LA_NAME_prod: 'ais-demo-prod'

on:
  workflow_dispatch:
    # Trigger the workflow every time the build workflow ran to complete
  workflow_run:
    workflows:
      - (classic) Logic App Infrastructure as Code Pipeline.
    types:
      - completed
  # Triggers when an environment file has been changed  
  push:
    paths:
      - "logic/**"
      - ".github/workflows/logicapp_deploy.yml"

permissions:
      id-token: write
      contents: read

jobs:
  logic_app_build: 
    name: Build 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package logic
      run: (cd logic; mkdir -p ../build-art; zip -r ../build-art/logic.zip .)
    - name: Upload app zip package
      uses: actions/upload-artifact@v2
      with:
        name: logic
        path: ./build-art/
        retention-days: 1 

  
  
  logic_app_deploy_dev: 
    name: Deploy Dev 
    runs-on: ubuntu-latest
    needs: [logic_app_build]
    environment: 
      name: dev
    steps: 
    - name: Checkout
      uses: actions/checkout@v1    

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUB_ID }}

    - uses: actions/download-artifact@master
      with:
        name: logic
        path: ./build-art/
        
    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.4.7
      id: la
      with:
        app-name: ${{ env.LA_NAME }}
        package: './build-art/logic.zip'        

    - name: Swap parameter files      
      id: params
      run: |              
        az functionapp deploy --resource-group ${{ secrets.RG_LA }} --name ${{ env.LA_NAME }} --src-path  logic/azure.parameters.json --type static --target-path parameters.json        

  logic_app_deploy_prod: 
    name: Deploy Prod 
    runs-on:  ubuntu-latest
    needs: [logic_app_deploy_dev]
    environment: 
      name: prod
    steps: 
    - name: Checkout
      uses: actions/checkout@v1    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUB_ID }}

    - uses: actions/download-artifact@master
      with:
        name: logic
        path: ./build-art/
        
    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.3.1
      id: la
      with:
        app-name: ${{secrets.RG_LA}}
        package: './build-art/logic.zip'


    - name: Swap parameter files       
      id: params
      run: az functionapp deploy --resource-group ${{ secrets.RG_LA }} --name ${{ env.LA_NAME_prod }} --src-path  logic/azure.parameters.json --type static --target-path parameters.json
